useMock: true
mockURL: https://serene-coast-56441.herokuapp.com/api/users/

db:
  driver: org.postgresql.Driver
  password: bf58000e9d4e39f4f4d855cb27e7e4651f40b02f645e6dfbd8434057f4e700ea
  url: jdbc:postgresql://ec2-52-5-176-53.compute-1.amazonaws.com:5432/degv4cu3gj4jnh
  username: qportnzpzjsair
entitymanager:
  packagesToScan: com
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl:
    auto: none
  show_sql: true

spring:
  datasource:
    base: ${db.url}
    driver-class-name: ${db.driver}
    password: ${db.password}
    tomcat:
      test-on-borrow: true
    url: ${spring.datasource.base}
    username: ${db.username}
    validation-query: select 1
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    contexts: postgres,text
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
