useMock: true
mockURL: https://serene-coast-56441.herokuapp.com/api/users/

db:
  driver: org.postgresql.Driver
  password: c16f59b38d2ade79c1bad116deec885715312d2247958a3e9a03b694d793fe12
  url: jdbc:postgresql://ec2-52-71-153-228.compute-1.amazonaws.com:5432/d80s8codr999s0
  username: yeogacdvtanfjl
entitymanager:
  packagesToScan: com
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl:
    auto: none
  show_sql: true

spring:
  datasource:
    base: ${db.url}
    driver-class-name: ${db.driver}
    password: ${db.password}
    tomcat:
      test-on-borrow: true
    url: ${spring.datasource.base}
    username: ${db.username}
    validation-query: select 1
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    contexts: postgres,text
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
